name: Build Wii

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devkitPro
        uses: devkitPro/gha-setup@v1
        with:
          project: wii

      - name: Build
        run: |
          make clean || true
          make

      - name: Check DOL
        run: |
          ls -lh ransom-wii.dol
          file ransom-wii.dol

      - name: Upload DOL
        uses: actions/upload-artifact@v4
        with:
          name: ransom-wii-dol
          path: ransom-wii.dol
